name: My First Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.19', '1.20' ]

    steps:

    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: go version

    - name: Copy from the root directory
      run: cp src/main.go .

    - name: Initialize a go module (if not exists)
      run: |
        if [ ! -f go.mod ]; then
          go mod init hello
        fi

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run
      run: go run .
